spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: insurance-policy-service

server:
  port: 8080
external:
  fraud-api:
    base-url: http://localhost:3001
messaging:
  exchange: policy.exchange
  routing-key: policy.status.updated
